classifier: /mnt/bil0/abdel/parallel-corpus-filtering/bicleaner-train/classifiers/bicleaner_dcce/en-de.classifier
classifier_type: random_forest
source_lang: en
target_lang: de
source_dictionary: /mnt/bil0/abdel/parallel-corpus-filtering/data/language_packs/en-de/dict-en.gz
target_dictionary: /mnt/bil0/abdel/parallel-corpus-filtering/data/language_packs/en-de/dict-de.gz
normalize_by_length: True
treat_oovs: True
qmax_limit: 20
disable_features_quest: True
good_examples: 4
wrong_examples: 4
good_test_examples: 1
wrong_test_examples: 1
good_test_histogram: [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
wrong_test_histogram: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
precision_histogram: [0.5000000, 0.5000000, 0.5000000, 1.0000000, 1.0000000, 1.0000000, nan, nan, nan, nan]
recall_histogram: [1.0000000, 1.0000000, 1.0000000, 1.0000000, 1.0000000, 1.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000]
accuracy_histogram: [0.5000000, 0.5000000, 0.5000000, 1.0000000, 1.0000000, 1.0000000, 0.5000000, 0.5000000, 0.5000000, 0.5000000]
length_ratio: 0.8443548
features_version: 2
